sudo: required
language: generic
services:
  - docker
before-install:
  - docker build -t manojvijay1990/docker-react-f Dockerfile.dev
script:
  - docker run -e CI=true manojvijay1990/docker-react npm run test
